In [1]:
from multi_dim_engine import Tensor
import numpy as np

In [6]:
def cross_entropy_loss(index_vector,scores) :
    # we get the probabilities matrix
    probabilities = softmax(scores)

    #set up for the advanced indexing
    rows = np.arange(probabilities.data.shape[0])
    true_prob = Tensor(probabilities.data[rows, index_vector])

    #calculating the losses 
    losses = -true_prob.log()
    N = true_prob.data.shape[0]
    
    full_loss = (1/N)*losses.sum()
    return full_loss

def softmax(scores) :
    expon = scores.exp()
    prob = expon / expon.sum(axe = -1)
    return prob
    

class Layer :

    def __init__(self, n_inputs , n_neurons) :
        self.w = Tensor(np.random.rand(n_neurons,n_inputs))
        self.b = Tensor(np.random.rand(n_neurons))

    def __call__(self,x) :
        output = x @ self.w.T() + self.b
        return output

    def parameters(self) :
        return [self.w , self.b]
    

    
class MLP : 

    def __init__(self, n_inputs,n_outputs) :
        size = [n_inputs] + n_outputs 
        self.layers = [Layer(size[i], size[i+1]) for i in range(len(size)-1)]

    def __call__(self,x) :
        for layer in self.layers : 
            x = layer(x).relu()
        return x 

    def parameters(self) :
        params = []
        for layer in self.layers :
            params.extend(layer.parameters())
        return params

In [10]:
scores = Tensor([[ 1 , 1.2 , 0.8],
                 [ 0.4 , 0.2 , 1.1],
                 [ 2 , 1.8 , 2.1]])

index_vector = np.array([2,2,0])

true = cross_entropy_loss(index_vector,scores)

true.backward()

print(scores.grad)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
